-- Create tables
CREATE TABLE IF NOT EXISTS public.players (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name character varying NOT NULL,
    CONSTRAINT players_pkey PRIMARY KEY (id),
    CONSTRAINT players_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.games (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    timestamp timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT games_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.game_participants (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    game_id uuid NULL DEFAULT gen_random_uuid(),
    player_id uuid NULL,
    team smallint NOT NULL,
    position smallint NOT NULL,
    tichu_call boolean NULL,
    grand_tichu_call boolean NULL,
    tichu_success boolean NULL,
    bomb_count smallint NULL,
    CONSTRAINT game_participants_pkey PRIMARY KEY (id),
    CONSTRAINT game_participants_game_id_fkey FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    CONSTRAINT game_participants_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS public.game_scores (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    game_id uuid NOT NULL,
    team smallint NOT NULL,
    score smallint NOT NULL,
    double_win boolean NOT NULL,
    total_score smallint NOT NULL,
    CONSTRAINT game_scores_pkey PRIMARY KEY (id),
    CONSTRAINT game_scores_game_id_fkey FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.rp_games (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    timestamp timestamp with time zone NOT NULL DEFAULT now(),
    number_of_players smallint NULL,
    CONSTRAINT rp_games_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rp_rounds (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    game_id uuid NULL,
    round_modifier character varying NULL,
    points smallint NULL,
    CONSTRAINT rp_rounds_pkey PRIMARY KEY (id),
    CONSTRAINT rp_rounds_game_id_fkey FOREIGN KEY (game_id) REFERENCES rp_games(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.rp_round_participants (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id uuid NULL,
    round_id uuid NULL,
    player_id uuid NULL,
    princess smallint NULL,
    points smallint NULL,
    CONSTRAINT rp_game_participants_pkey PRIMARY KEY (id),
    CONSTRAINT rp_game_participants_game_id_fkey FOREIGN KEY (game_id) REFERENCES rp_games(id) ON DELETE CASCADE,
    CONSTRAINT rp_round_participants_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT rp_round_participants_round_id_fkey FOREIGN KEY (round_id) REFERENCES rp_rounds(id)
);